### ISSUE TITLE
issues running on Mac OS X El captain

### ISSUE THREAD

**Issue by daniel0076** [sysprog21/concurrent-ll#2]
測試的OS X version: El captain 10.11.6
`make bench`後會出錯
- malloc.h not found
  
  發現mac的malloc.h位於`/usr/include/malloc/`下
  `/include/random.h`中的`#include <malloc.h>`改為`#include <malloc/malloc.h>`
- ld fail , `_memaling` not found
  
  mac下似乎只有posix_memalign，`/include/random.h`中的metaling那行改為`posix_memalign((void **)&seeds,64, 64);`
- `nproc` not found
  用別的方法來拿logic處理器數量
  `/scripts/config`第六行改為`num_cores=$(sysctl -n hw.ncpu);`

給用mac的人參考
//結果有人先送PR了

**Comment by coldnew** [comment]
You can install coreutils to get the nproc command. Following are homebrew example:

```
brew install coreutils
```

**Comment by daniel0076** [comment]
Oh that is better.
I didn't think of getting the `nproc` tool, so I try to fix it with what OS X already have.
Thank you very much for the info.

**Comment by jserv** [comment]
@daniel0076 : You can send another pull request to mention `nproc` or further modifications.
